FROM node:20-bullseye AS base
WORKDIR /app
COPY package.json pnpm-workspace.yaml ./
COPY apps/backend/package.json ./apps/backend/
COPY apps/frontend/package.json ./apps/frontend/
COPY packages/shared/package.json ./packages/shared/
RUN corepack enable
RUN pnpm install --frozen-lockfile=false

COPY . .
RUN pnpm --filter @kube-suite/backend build

CMD ["pnpm", "--filter", "@kube-suite/backend", "start"]
